nama = input("Masukan nama anda: ")
usia = input('Berapa usia anda: ')
usia = int(usia)
pekerjaan = input('Masukan pekerjaan anda: ')
hobi = input("Masukan hobi anda: ")

print("================================")
print("       KARTU NAMA DIGITAL")
print("================================")
print(f'Nama : {nama}')
print(f'Usia : {usia}')
print(f'Pekerjaan : {pekerjaan}')
print(f'Hobi : {hobi}')
print("================================")
